from __future__ import annotations

from pathlib import Path
from dataclasses import dataclass
from typing import TYPE_CHECKING

from ..component_readiness import calculate_component_readiness
from ..errors import InvalidGraphError
from ..storage.preparation_execution import prepare_component_unit
from ..storage.preparation_footprint import read_preparation_footprint
from ..storage.preparation_guards import hold_preparation_guards
from ..storage.membership_observation import (
    read_membership_change, membership_needs_fresh_preparation, membership_repair_lines,
)
from ..storage.membership_footprint import read_membership_preparation_footprint
from ..storage.membership_preparation import MembershipPreparation

if TYPE_CHECKING:
    from ..system import MicroWorkflow


@dataclass(frozen=True)
class FreshComponentSelection:
    shape_json: str
    components: tuple[tuple[str, ...], ...]


def observe_programmatic_fresh_preparation(workflow, nodes):
    """Refuse blocked external parents before an independent run changes state."""
    with workflow.lock:
        snapshot = workflow.topology.snapshot()
        components = tuple(workflow.topology.execution_components(nodes))
        if not components or set(nodes) - set(workflow.graph_obj):
            raise ValueError('Fresh preparation requires a nonempty current selection')
        selected = set(components)
        parents = {
            component: workflow.component_predecessor_components(set(component)) - selected
            for component in components
        }
    external = sorted({parent for group in parents.values() for parent in group})
    states = workflow.storage.read_component_states(
        external, expected_shape=snapshot.shape_json, allow_missing=True,
    )
    for component, predecessors in parents.items():
        observed = [states[parent] for parent in predecessors]
        if any(state is None for state in observed) or calculate_component_readiness(
            (state['lifecycle'], state['stability'], state['instability_origin'])
            for state in observed
        ) is None:
            raise InvalidGraphError(f'Hoeflein component {list(component)} is not ready for fresh preparation')
    return FreshComponentSelection(snapshot.shape_json, components)


def prepare_admitted_programmatic_components(workflow, nodes, selection):
    context = workflow.execution_session_context
    if (context is None or context[2] != selection.shape_json
            or set(context[1].values()) != set(selection.components)):
        raise RuntimeError('Fresh preparation selection changed during admission')
    observed = observe_programmatic_fresh_preparation(workflow, nodes)
    if observed != selection:
        raise RuntimeError('Fresh preparation selection changed during admission')
    return prepare_fresh_components(
        workflow.storage.project_dir, workflow, [set(component) for component in selection.components],
    )


def prepare_fresh_components(
    root: Path,
    workflow: MicroWorkflow,
    components: list[set[str]],
    *,
    keep_trace: bool = False,
    operation: str = 'run',
) -> dict[str, int]:
    """Prepare a full CLI or independent programmatic component selection.

    Jobs generated by selected producer components are deleted so they can be
    recreated deterministically. The first component is the user's explicit
    selection and all of its remaining jobs are reset. Later components preserve
    jobs from unselected incoming branches.
    """
    if not components:
        raise ValueError('Fresh preparation requires a nonempty component selection')
    with workflow.storage.interprocess_lock('active-run-state'):
        context = workflow.execution_session_context
        with workflow.lock:
            snapshot = workflow.topology.snapshot()
            selected = [workflow.component_id(component) for component in components]
        storage = workflow.storage
        if context is None:
            storage.refuse_live_sessions_for_reset()
            pending = read_membership_change(storage.db_connection(), snapshot, selected)
            for line in membership_repair_lines(pending):
                print(line)
            storage.register_component_topology(snapshot)
        elif snapshot.shape_json != context[2]:
            raise RuntimeError('Fresh preparation graph changed after admission')
        change = read_membership_change(storage.db_connection(), snapshot, selected)
        if membership_needs_fresh_preparation(change):
            footprint = read_membership_preparation_footprint(
                storage, change, start_component=selected[0], keep_trace=keep_trace,
            )
            session_id = None if context is None else context[0]
            preparation = MembershipPreparation(storage, change, footprint, session_id, operation)
            observations = {unit.component: storage.get_component_state(unit.component) for unit in footprint.units}
            removed = {}
            with hold_preparation_guards(
                storage, footprint, session_id, observations, membership_preparation=preparation,
            ) as guard_id:
                for unit in footprint.units:
                    changed = prepare_component_unit(
                        storage, root, unit, observations[unit.component], session_id, guard_id,
                        operation, keep_trace=keep_trace, membership_preparation=preparation,
                    )
                    for node, count in changed.items():
                        removed[node] = removed.get(node, 0) + count
                preparation.finish(guard_id)
            return removed
        observations = {
            component: (
                storage.read_component_reset_preparation(component, expected_shape=snapshot.shape_json)
                if context is None else storage.read_component_fresh_preparation(
                    context[0], component, expected_shape=context[2],
                )
            ) for component in selected
        }
        return _prepare_observed_components(root, workflow, selected, observations, context,
                                             keep_trace=keep_trace, operation=operation,
                                             target_shape=snapshot.shape_json)


def _prepare_observed_components(root, workflow, components, observations, context, *, keep_trace, operation,
                                 target_shape):
    storage = workflow.storage
    footprint = read_preparation_footprint(storage, components, keep_trace=keep_trace)
    session_id = None if context is None else context[0]
    removed = {}
    with hold_preparation_guards(storage, footprint, session_id, observations) as guard_id:
        for unit in footprint.units:
            changed = prepare_component_unit(storage, root, unit, observations[unit.component], session_id,
                                             guard_id, operation, keep_trace=keep_trace, target_shape=target_shape)
            for node, count in changed.items():
                removed[node] = removed.get(node, 0) + count
    return removed
