from __future__ import annotations

from pathlib import Path
from dataclasses import dataclass
from typing import TYPE_CHECKING

from ..component_readiness import calculate_component_readiness
from ..errors import InvalidGraphError
from ..storage.job_preparation import apply_job_preparation, read_job_preparation
from ..storage.preparation_files import stage_preparation_files

if TYPE_CHECKING:
    from ..system import MicroWorkflow


@dataclass(frozen=True)
class FreshComponentSelection:
    shape_json: str
    components: tuple[tuple[str, ...], ...]


def observe_programmatic_fresh_preparation(workflow, nodes):
    """Refuse blocked external parents before an independent run changes state."""
    with workflow.lock:
        snapshot = workflow.topology.snapshot()
        components = tuple(workflow.topology.execution_components(nodes))
        if not components or set(nodes) - set(workflow.graph_obj):
            raise ValueError('Fresh preparation requires a nonempty current selection')
        selected = set(components)
        parents = {
            component: workflow.component_predecessor_components(set(component)) - selected
            for component in components
        }
    external = sorted({parent for group in parents.values() for parent in group})
    states = workflow.storage.read_component_states(
        external, expected_shape=snapshot.shape_json, allow_missing=True,
    )
    for component, predecessors in parents.items():
        observed = [states[parent] for parent in predecessors]
        if any(state is None for state in observed) or calculate_component_readiness(
            (state['lifecycle'], state['stability'], state['instability_origin'])
            for state in observed
        ) is None:
            raise InvalidGraphError(f'Hoeflein component {list(component)} is not ready for fresh preparation')
    return FreshComponentSelection(snapshot.shape_json, components)


def prepare_admitted_programmatic_components(workflow, nodes, selection):
    context = workflow.execution_session_context
    if (context is None or context[2] != selection.shape_json
            or set(context[1].values()) != set(selection.components)):
        raise RuntimeError('Fresh preparation selection changed during admission')
    observed = observe_programmatic_fresh_preparation(workflow, nodes)
    if observed != selection:
        raise RuntimeError('Fresh preparation selection changed during admission')
    return prepare_fresh_components(
        workflow.storage.project_dir, workflow, [set(component) for component in selection.components],
    )


def prepare_fresh_components(
    root: Path,
    workflow: MicroWorkflow,
    components: list[set[str]],
    *,
    keep_trace: bool = False,
) -> dict[str, int]:
    """Prepare a full CLI or independent programmatic component selection.

    Jobs generated by selected producer components are deleted so they can be
    recreated deterministically. The first component is the user's explicit
    selection and all of its remaining jobs are reset. Later components preserve
    jobs from unselected incoming branches.
    """
    if not components:
        raise ValueError('Fresh preparation requires a nonempty component selection')
    with workflow.storage.interprocess_lock('active-run-state'):
        context = workflow.execution_session_context
        with workflow.lock:
            snapshot = workflow.topology.snapshot()
            selected = [workflow.component_id(component) for component in components]
        if context is None:
            workflow.storage.refuse_live_sessions_for_reset()
            workflow.storage.register_component_topology(snapshot)
            observations = {
                component: workflow.storage.read_component_reset_preparation(component, expected_shape=snapshot.shape_json)
                for component in selected
            }
        else:
            if snapshot.shape_json != context[2]:
                raise RuntimeError('Fresh preparation graph changed after admission')
            observations = {
                component: workflow.storage.read_component_fresh_preparation(
                    context[0], component, expected_shape=context[2],
                ) for component in selected
            }
        return _prepare_observed_components(root, workflow, selected, observations, context, keep_trace=keep_trace)


def _prepare_observed_components(root, workflow, components, observations, context, *, keep_trace):
    selected = set(components)
    preparations = {
        component: read_job_preparation(
            workflow.storage, component, selected, reset_retained=True, preserve_external=position > 0,
        ) for position, component in enumerate(components)
    }
    selected_nodes = {node for component in components for node in component}
    outside = read_job_preparation(
        workflow.storage, sorted(set(workflow.graph_obj) - selected_nodes), selected,
        reset_retained=False, preserve_external=True,
    )
    removed = {}
    for component in components:
        plans = preparations[component]
        with stage_preparation_files(root, plans):
            if context is None:
                workflow.storage.complete_component_reset_preparation(
                    component, expected_state=observations[component], job_preparation=plans, keep_trace=keep_trace,
                )
            else:
                workflow.storage.complete_component_fresh_preparation(
                    context[0], component, expected_state=observations[component],
                    job_preparation=plans, keep_trace=keep_trace,
                )
        for plan in plans:
            if plan.delete_ids:
                removed[plan.node] = len(plan.delete_ids)
        workflow.storage.notify_queue_changes(component)
    for plan in outside:
        if not plan.delete_ids and (keep_trace or not plan.orphan_ids):
            continue
        with stage_preparation_files(root, [plan]):
            workflow.storage.submit_db_mutation(
                lambda connection: apply_job_preparation(connection, [plan], keep_trace=keep_trace),
            )
        if plan.delete_ids:
            removed[plan.node] = len(plan.delete_ids)
        workflow.storage.notify_queue_change(plan.node)
    return removed
