from __future__ import annotations

from pathlib import Path

from micro_workflow_manager.models import QUEUED
from micro_workflow_manager.system import MicroWorkflow

from .files import remove_dir, remove_path, safe_node_dir, safe_node_name
from .graph_utils import component_topological_nodes
from .validation import require_node

def is_all_nodes_request(nodes: list[str]) -> bool:
    if any(item == "*" for item in nodes):
        return True

    # On shells that expand '*' before Python sees it, mwf clean * may arrive
    # as the visible names in the current directory. Treat that exact expansion
    # as the same all-nodes request.
    try:
        visible_cwd_entries = sorted(
            path.name for path in Path.cwd().iterdir()
            if not path.name.startswith(".")
        )
    except OSError:
        return False

    return len(nodes) > 1 and sorted(nodes) == visible_cwd_entries

def resolve_node_targets(workflow: MicroWorkflow, requested: list[str]) -> list[str]:
    if not requested:
        raise RuntimeError("No node specified")

    if is_all_nodes_request(requested):
        return component_topological_nodes(workflow)

    seen: set[str] = set()
    nodes: list[str] = []

    for item in requested:
        node = safe_node_name(item)
        require_node(workflow, node)
        if node not in seen:
            seen.add(node)
            nodes.append(node)

    return nodes

def clean_node(
    root: Path,
    workflow: MicroWorkflow,
    node: str,
    remove_input: bool = False,
):
    """User-facing clean/wipe.

    This is intentionally destructive for jobs: `mwf clean node` means the node
    is no longer finished and has no queued/done jobs on disk. Router-declared
    default jobs are recreated the next time the workflow is loaded. Dynamic
    jobs must be regenerated by rerunning their upstream nodes.
    """
    node_dir = safe_node_dir(root, node)

    remove_dir(node_dir / "output")
    remove_dir(node_dir / "jobs")

    if remove_input:
        remove_dir(node_dir / "input")

    workflow.storage.init_node_folders(node)
    workflow.storage.rebuild_job_index(node)
    workflow.storage.set_node_status(node, QUEUED)

def reset_node_for_run(
    root: Path,
    workflow: MicroWorkflow,
    node: str,
    *,
    remove_parented_jobs: bool = False,
    mark_queued: bool = True,
):
    """Reset a node while preserving its job definitions.

    This keeps each job's job.json and input.json, but removes the generated
    run artifacts so the job is queued again. When remove_parented_jobs=True,
    jobs created by upstream runs are deleted instead of preserved; this lets
    runfrom keep router.create_job(...) jobs on descendants while avoiding stale
    dynamic jobs from earlier runs.
    """
    node_dir = safe_node_dir(root, node)

    remove_dir(node_dir / "output")

    jobs_dir = node_dir / "jobs"
    jobs_dir.mkdir(parents=True, exist_ok=True)

    for job_dir in list(jobs_dir.iterdir()):
        if not job_dir.is_dir() or not job_dir.name.isdigit():
            continue

        if remove_parented_jobs:
            job_data = workflow.storage.read_json(job_dir / "job.json", default={})
            if job_data.get("parent") is not None:
                remove_path(job_dir)
                continue

        # Remove the known generated artifacts directly instead of scanning every
        # child path. On nodes with thousands of jobs this removes a large amount
        # of startup bookkeeping before the actual run begins. A missing
        # status.json is now interpreted as queued by FileStorage.
        remove_path(job_dir / "status.json")
        remove_path(job_dir / "output.json")
        remove_path(job_dir / "files")

    workflow.storage.init_node_folders(node)
    workflow.storage.rebuild_job_index(node)
    if mark_queued:
        workflow.storage.set_node_status(node, QUEUED)

def reset_job_for_run(
    root: Path,
    workflow: MicroWorkflow,
    node: str,
    job_id: int,
    *,
    mark_queued: bool = True,
):
    """Reset one job while preserving job.json and input.json."""
    node_dir = safe_node_dir(root, node)
    job_dir = node_dir / "jobs" / str(job_id)

    if not job_dir.is_dir():
        raise RuntimeError(f"Job does not exist: {node}/{job_id}")

    remove_path(job_dir / "output.json")
    remove_path(job_dir / "files")
    workflow.storage.set_job_status(node, job_id, QUEUED)

    if mark_queued:
        workflow.storage.set_node_status(node, QUEUED)

def clear_node(root: Path, workflow: MicroWorkflow, node: str):
    node_dir = safe_node_dir(root, node)
    remove_dir(node_dir / "output")
    remove_dir(node_dir / "jobs")
    workflow.storage.init_node_folders(node)
    workflow.storage.rebuild_job_index(node)
    workflow.storage.set_node_status(node, QUEUED)
